"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Context={job:{title:string;company:string;description:string;isAvailable:boolean};resumes:{id:string;title:string;updatedAt:string}[];selectedResume?:{id:string;updatedAt:string};scan?:{id:string;score:number;stale:boolean};interview?:{id:string;status:string;stale:boolean};application?:{id:string;status:string};preparation:{id:string;title:string}[];eligibility:{status:string;notice:string;checks:{label:string;status:string;detail:string}[]}};
export function JobWorkspace({jobId,onResumeSelect,available}:{jobId:string;available:boolean;onResumeSelect:(id:string)=>void}){const [context,setContext]=useState<Context>();const [resumeId,setResumeId]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch(`/api/candidate/job-workspaces/${jobId}`);const j=await r.json();if(!r.ok)throw new Error(j.error);setContext(j);setResumeId(j.selectedResume?.id || "");onResumeSelect(j.selectedResume?.id || "");}
 useEffect(()=>{load().catch(e=>setNotice(e.message));},[jobId]);
 async function select(id:string){setBusy(true);try{const r=await fetch(`/api/candidate/job-workspaces/${jobId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resumeId:id})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();setNotice("");}catch(e){setNotice(e instanceof Error?e.message:"Could not save selection.");}finally{setBusy(false);}}
 async function analyze(){if(!context || !resumeId)return;setBusy(true);try{const r=await fetch("/api/ats/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resumeId,targetJobTitle:context.job.title,companyName:context.job.company,jobDescription:context.job.description})});const j=await r.json();if(!r.ok)throw new Error(j.error);const attach=await fetch(`/api/candidate/job-workspaces/${jobId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resumeId,scanId:j.scanId})});if(!attach.ok)throw new Error("The scan was saved, but job context changed. Review scan history.");await load();setNotice("Comparison saved for this resume version.");}catch(e){setNotice(e instanceof Error?e.message:"Comparison failed. Retry.");}finally{setBusy(false);}}
 return <section className="border rounded-2xl p-5 space-y-4 bg-neutral-50"><h2 className="font-bold text-lg">Prepare for this opportunity</h2><p role="status">{notice}</p>{context && <><p>{available && context.job.isAvailable?"Applications open":"This opening is unavailable. Your saved preparation remains accessible."}</p><label>Resume for this job<select disabled={busy} className="border rounded p-2 ml-3" value={resumeId} onChange={e=>select(e.target.value)}><option value="">Select a resume</option>{context.resumes.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>{resumeId && <p className="text-xs">Version saved {new Date(context.selectedResume!.updatedAt).toLocaleString()}</p>}<div className="flex gap-5 flex-wrap"><Link className="underline" href={resumeId?`/resume?resumeId=${resumeId}`:"/resume"}>Edit resume</Link><button disabled={busy || !resumeId} onClick={analyze} className="underline disabled:opacity-50">{busy?"Working...":"Compare resume"}</button>{context.scan && <Link className="underline" href={`/ats-checker?scanId=${context.scan.id}`}>{context.scan.stale?"Previous scan needs refresh":`View comparison (${context.scan.score})`}</Link>}{resumeId && <Link className="underline" href={`/mock-interview?jobId=${jobId}`}>Practise interview</Link>}{context.interview && <p className="text-sm">Latest interview: {context.interview.status.replaceAll("_"," ")}{context.interview.stale?" (earlier resume or job version)":" (current preparation context)"}. <Link className="underline" href="/mock-interview">Open interview history</Link></p>}{context.application && <Link className="underline" href={`/jobs/applications/${context.application.id}`}>Application: {context.application.status.replaceAll("_"," ")}</Link>}</div><div><strong>Eligibility: {context.eligibility.status.replaceAll("_"," ")}</strong><p className="text-sm">{context.eligibility.notice}</p>{context.eligibility.checks.map(c=><p key={c.label} className="text-sm">{c.label}: {c.status.replaceAll("_"," ")} | {c.detail}</p>)}</div><div><strong>Relevant practice</strong><div className="flex gap-3 flex-wrap">{context.preparation.map(t=><Link className="underline text-sm" key={t.id} href={`/preparation?topicId=${t.id}`}>{t.title}</Link>)}</div></div></>}</section>;
}
