"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
type Item={id:string;title:string;status:string;instituteName:string;createdAt:string;expiresAt:string;commentCount:number;openComments:number;preview:string|null};
const labels:Record<string,string>={REQUESTED:"Awaiting feedback",REVIEWED:"Feedback received",REVOKED:"Access revoked",EXPIRED:"Sharing expired"};
export default function FeedbackInbox() {
  const [items,setItems]=useState<Item[]>([]),[status,setStatus]=useState("ALL"),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/candidate/feedback?${new URLSearchParams({status,search:query,page:String(page)})}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error || "Unable to load feedback.");setItems(j.reviews);setTotal(j.total);}catch(e){setItems([]);setError(e instanceof Error?e.message:"Unable to load feedback.");}finally{setLoading(false);}},[status,query,page]);
  useEffect(()=>{void load();},[load]);
  return <div className="max-w-5xl mx-auto space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-bold">Feedback inbox</h1><p className="text-neutral-600 mt-2">Your institute resume reviews, comments and revision history.</p></div><Link href="/resume" className="underline self-center">Request a review in Resume Builder</Link></div>
    <section className="bg-white border rounded-xl p-5 text-sm space-y-2"><p>Each review concerns the frozen resume copy you shared. Editing your resume keeps that copy and its feedback unchanged.</p><p>Revoked and expired feedback remains available to you. New sharing requires your current institute membership and mentor-sharing consent.</p><Link href="/settings" className="underline">Feedback alert preferences</Link></section>
    <form onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search);}} className="flex flex-wrap gap-3"><label className="text-sm">Search resume title<input maxLength={150} value={search} onChange={e=>setSearch(e.target.value)} className="block border rounded-lg p-2 mt-1"/></label><label className="text-sm">Review status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} className="block border rounded-lg p-2 mt-1"><option value="ALL">All reviews</option>{Object.entries(labels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><button disabled={loading} className="border rounded-lg px-4 py-2 self-end">Search feedback</button><button disabled={loading} type="button" onClick={()=>void load()} className="underline self-end py-2">Refresh inbox</button></form>
    {error && <p role="alert" className="text-red-700">{error}</p>}{loading ? <p role="status">Loading reviews…</p> : <><p className="text-sm text-neutral-600">{total} {total===1 ? "review" : "reviews"} matching these filters</p>{items.map(item=><article key={item.id} className="bg-white border rounded-2xl p-5 space-y-3"><div className="flex justify-between flex-wrap gap-2"><h2 className="font-bold text-lg"><Link className="underline" href={`/feedback/${item.id}`}>{item.title}</Link></h2><span className="border rounded-full px-3 py-1 text-xs">{labels[item.status]}</span></div><p className="text-sm text-neutral-600">{item.instituteName} · Requested {new Date(item.createdAt).toLocaleDateString()} · Access expires {new Date(item.expiresAt).toLocaleDateString()}</p><p className="text-sm">{item.commentCount} {item.commentCount===1 ? "comment" : "comments"} · {item.openComments} to address</p>{item.preview && <p className="text-sm whitespace-pre-wrap">{item.preview}</p>}<Link className="underline text-sm" href={`/feedback/${item.id}`}>Open feedback and revision options</Link></article>)}{!items.length && !error && <section className="bg-white border rounded-xl p-6"><h2 className="font-bold">No reviews match these filters</h2><p className="text-sm mt-2">Choose a saved resume in Resume Builder to request your first institute review.</p></section>}<div className="flex gap-4 text-sm items-center"><button disabled={page===1 || loading} onClick={()=>setPage(p=>p-1)} className="underline disabled:opacity-40">Previous page</button><span>Page {page} of {Math.max(1,Math.ceil(total/25))}</span><button disabled={page*25>=total || loading} onClick={()=>setPage(p=>p+1)} className="underline disabled:opacity-40">Next page</button></div></>}
  </div>;
}
