import test from "node:test";
import assert from "node:assert/strict";
import {db} from "../lib/db";
import {stubMethod} from "./fixtures";
import {saveApplicantEvaluation,publishApplicantUpdate,validateEvaluation,readEvaluation} from "../lib/company/applicant-tools";
import {emptyEvaluation} from "../lib/company/applicant-tools-types";
import {filterPipeline} from "../lib/company/pipeline-filters";
import {getApplicationDetails} from "../lib/jobs/jobs-service";
import {getCompanyApplications} from "../lib/company/company-service";
import {createRequire} from "node:module";
import {signToken} from "../lib/auth/jwt";
import * as reviewRoute from "../app/api/company/applications/[id]/review/route";
import {latestApplicationUpdate} from "../lib/jobs/application-updates";
const id="444444444444444444444444",revision=new Date('2026-10-06T00:00:00Z');
const require=createRequire(import.meta.url),{RequestCookies}=require('next/dist/compiled/@edge-runtime/cookies');
async function authenticated(role:string,run:()=>Promise<void>){const token=await signToken({userId:'owner',role,email:'qa@example.test',sessionId:crypto.randomUUID()});const restores=[stubMethod(require('next/headers'),'cookies',async()=>new RequestCookies(new Headers({cookie:`vantory_session=${token}`}))),stubMethod(db.authSession,'findUnique',async()=>({userId:'owner',revokedAt:null,expiresAt:new Date(Date.now()+86400000)})),stubMethod(db.user,'findUnique',async()=>({id:'owner',role,name:'QA',email:'qa@example.test',isActive:true,emailVerifiedAt:revision,createdAt:revision}))];try{await run();}finally{restores.reverse().forEach(r=>r());}}
function request(body:unknown){return new Request('http://localhost/api/company/applications/review',{method:'PATCH',body:JSON.stringify(body)});}
const app={id,status:'INTERVIEW',updatedAt:revision,createdAt:revision,jobId:'job',job:{companyUserId:'owner',company:'QA',title:'QA role'},notes:'PRIVATE NOTES',evaluationJson:JSON.stringify({...emptyEvaluation,concerns:'PRIVATE EVALUATION'}),timelineJson:JSON.stringify([{status:'APPLIED',title:'Applied',timestamp:revision.toISOString()}])};
test('Public reminder dates remain unchanged by private edits, and employer messages alert applied candidates',()=>{const publicAt='2026-09-01T00:00:00Z';assert.deepEqual(latestApplicationUpdate({...app,timelineJson:JSON.stringify([{status:'INTERVIEW',timestamp:publicAt}])}),{title:'INTERVIEW',at:publicAt});assert.equal(latestApplicationUpdate({...app,status:'APPLIED'}),null);assert.deepEqual(latestApplicationUpdate({...app,status:'APPLIED',timelineJson:JSON.stringify([{kind:'EMPLOYER_UPDATE',status:'APPLIED',timestamp:revision.toISOString(),note:'QA next step'}])}),{title:'Update from hiring team',at:revision.toISOString()});assert.equal(latestApplicationUpdate({...app,timelineJson:'{}'}),null);});
test('Structured evaluations validate bounded fields and retain legacy empty evaluations',()=>{assert.deepEqual(readEvaluation(null),emptyEvaluation);assert.deepEqual(readEvaluation('malformed'),emptyEvaluation);assert.throws(()=>validateEvaluation({...emptyEvaluation,strengths:'x'.repeat(2001)}),/2,000/);assert.throws(()=>validateEvaluation({...emptyEvaluation,interviewOutcome:'OFFERED'}),/valid/);assert.equal(validateEvaluation({...emptyEvaluation,strengths:' Evidence '}).strengths,'Evidence');});
test('Private evaluation changes only its own storage with employer ownership and fresh revision',async()=>{let writes=0;const restores=[stubMethod(db.jobApplication,'findUnique',async()=>app),stubMethod(db.jobApplication,'updateMany',async({where,data}:any)=>{writes++;assert.equal(where.updatedAt,revision);assert.deepEqual(Object.keys(data),['evaluationJson','updatedAt']);return {count:1};})];try{const saved=await saveApplicantEvaluation('owner',id,{evaluation:{...emptyEvaluation,strengths:'QA evidence'},expectedUpdatedAt:revision.toISOString()});assert.equal(saved.evaluation.strengths,'QA evidence');await assert.rejects(()=>saveApplicantEvaluation('foreign',id,{evaluation:emptyEvaluation,expectedUpdatedAt:revision.toISOString()}),/unavailable/);await assert.rejects(()=>saveApplicantEvaluation('owner',id,{evaluation:emptyEvaluation,expectedUpdatedAt:'2026-10-05T00:00:00Z'}),/changed/);assert.equal(writes,1);}finally{restores.reverse().forEach(r=>r());}});
test('Candidate updates append public text without private notes or evaluations and preserve status',async()=>{let data:any;const restores=[stubMethod(db.jobApplication,'findUnique',async()=>app),stubMethod(db.jobApplication,'updateMany',async(q:any)=>{data=q.data;assert.equal(q.where.status,'INTERVIEW');return {count:1};})];try{const result=await publishApplicantUpdate('owner',id,{message:' QA ONLY — Next steps in your timeline ',expectedUpdatedAt:revision.toISOString()});assert.deepEqual(Object.keys(data),['timelineJson','updatedAt']);assert.equal(JSON.parse(data.timelineJson).length,2);assert.equal(result.event.note,'QA ONLY — Next steps in your timeline');assert.doesNotMatch(data.timelineJson,/PRIVATE/);}finally{restores.reverse().forEach(r=>r());}});
test('Withdrawn, foreign, stale and malformed updates cannot publish',async()=>{let current={...app},writes=0;const restores=[stubMethod(db.jobApplication,'findUnique',async()=>current),stubMethod(db.jobApplication,'updateMany',async()=>{writes++;return {count:1};})];try{await assert.rejects(()=>publishApplicantUpdate('foreign',id,{message:'QA',expectedUpdatedAt:revision.toISOString()}),/unavailable/);await assert.rejects(()=>publishApplicantUpdate('owner',id,{message:'QA',expectedUpdatedAt:'2026-10-05T00:00:00Z'}),/changed/);current={...app,status:'WITHDRAWN'};await assert.rejects(()=>publishApplicantUpdate('owner',id,{message:'QA',expectedUpdatedAt:revision.toISOString()}),/withdrew/);current={...app,timelineJson:'{}'};await assert.rejects(()=>publishApplicantUpdate('owner',id,{message:'QA',expectedUpdatedAt:revision.toISOString()}),/history/);await assert.rejects(()=>publishApplicantUpdate('owner',id,{message:' ',expectedUpdatedAt:revision.toISOString()}),/Write/);assert.equal(writes,0);}finally{restores.reverse().forEach(r=>r());}});
test('Concurrent review writes report conflict for both private and public actions',async()=>{const restores=[stubMethod(db.jobApplication,'findUnique',async()=>app),stubMethod(db.jobApplication,'updateMany',async()=>({count:0}))];try{await assert.rejects(()=>saveApplicantEvaluation('owner',id,{evaluation:emptyEvaluation,expectedUpdatedAt:revision.toISOString()}),/changed/);await assert.rejects(()=>publishApplicantUpdate('owner',id,{message:'QA',expectedUpdatedAt:revision.toISOString()}),/changed/);}finally{restores.reverse().forEach(r=>r());}});
test('Candidate detail omits private evaluation and notes while preserving public update history',async()=>{const restore=stubMethod(db.jobApplication,'findFirst',async({where}:any)=>{assert.equal(where.userId,'candidate');return {...app,resume:null};});try{const result=await getApplicationDetails('candidate',id);assert.ok(result?.timeline.length);assert.doesNotMatch(JSON.stringify(result),/PRIVATE|evaluationJson|employerNotes/);}finally{restore();}});
test('Employer pipeline reads private evaluation only after filtering owned jobs',async()=>{const restores=[stubMethod(db.jobPosting,'findMany',async()=>[{id:'job'}]),stubMethod(db.jobApplication,'findMany',async({where}:any)=>{assert.deepEqual(where.jobId,{in:['job']});return [{...app,resume:null,user:{id:'candidate',name:'QA',email:'qa@example.invalid',profile:null}}];})];try{const result=await getCompanyApplications('owner');assert.equal(result[0].evaluation.concerns,'PRIVATE EVALUATION');}finally{restores.reverse().forEach(r=>r());}});
test('Pipeline filters combine role, status, inclusive local dates and stable sorting without mutating source',()=>{const rows=[{id:'b',candidateName:'Zoe',candidateEmail:'qa@example.invalid',jobTitle:'QA role',jobId:'job',status:'INTERVIEW',appliedAt:'2026-10-06T12:00:00',updatedAt:'2026-10-06T13:00:00'},{id:'a',candidateName:'Amy',candidateEmail:'other@example.invalid',jobTitle:'Other',jobId:'other',status:'APPLIED',appliedAt:'2026-10-05T12:00:00',updatedAt:'2026-10-07T13:00:00'}];const base={search:'',jobId:'ALL',status:'ALL',from:'',to:'',sort:'NEWEST' as const};assert.deepEqual(filterPipeline(rows,{...base,search:'QA',jobId:'job',status:'INTERVIEW',from:'2026-10-06',to:'2026-10-06'}).map(a=>a.id),['b']);assert.deepEqual(filterPipeline(rows,{...base,sort:'UPDATED'}).map(a=>a.id),['a','b']);assert.deepEqual(filterPipeline(rows,{...base,sort:'NAME'}).map(a=>a.id),['a','b']);assert.deepEqual(rows.map(a=>a.id),['b','a']);assert.equal(filterPipeline(rows,{...base,from:'2026-10-07'}).length,0);});
test('Review API blocks unauthenticated candidates and institute admins',async()=>{const restores=[stubMethod(require('next/headers'),'cookies',async()=>new RequestCookies(new Headers()))];try{assert.equal((await reviewRoute.PATCH(request({}),{params:Promise.resolve({id})})).status,401);}finally{restores.reverse().forEach(r=>r());}for(const role of ['CANDIDATE','INSTITUTE_ADMIN'])await authenticated(role,async()=>{assert.equal((await reviewRoute.PATCH(request({action:'evaluation'}),{params:Promise.resolve({id})})).status,403);});});
test('Review API preserves conflict codes and sends successful employer results with private no-store caching',async()=>{await authenticated('COMPANY_ADMIN',async()=>{let count=0;const restores=[stubMethod(db.jobApplication,'findUnique',async()=>app),stubMethod(db.jobApplication,'updateMany',async()=>({count:count++ ? 1 : 0}))];try{const body={action:'evaluation',evaluation:emptyEvaluation,expectedUpdatedAt:revision.toISOString()};assert.equal((await reviewRoute.PATCH(request(body),{params:Promise.resolve({id})})).status,409);const response=await reviewRoute.PATCH(request(body),{params:Promise.resolve({id})});assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal((await reviewRoute.PATCH(request({action:'unknown'}),{params:Promise.resolve({id})})).status,400);}finally{restores.reverse().forEach(r=>r());}});});
