import test from "node:test";
import assert from "node:assert/strict";
import {createRequire} from "node:module";
import {db} from "../lib/db";
import {stubMethod} from "./fixtures";
import {feedbackStatus,commentContext,candidateFeedback,feedbackReminders} from "../lib/resume/feedback";
import {emptyResumeData} from "../lib/resume/types";
import {defaultCareer,defaultPreferences} from "../lib/candidate/profile";
import {signToken} from "../lib/auth/jwt";
import * as feedbackRoute from "../app/api/candidate/feedback/route";
import * as reviewsRoute from "../app/api/candidate/resume-reviews/route";
import * as profileRoute from "../app/api/candidate/profile/route";
const require=createRequire(import.meta.url),{RequestCookies}=require("next/dist/compiled/@edge-runtime/cookies");
const owner="444444444444444444444444",resumeId="555555555555555555555555",reviewId="666666666666666666666666",instituteId="777777777777777777777777",commentId="888888888888888888888888";
const original=new Date("2026-10-01T00:00:00Z"),revised=new Date("2026-10-02T00:00:00Z"),future=new Date(Date.now()+86400000);
const snapshot={...emptyResumeData,projects:[{id:"project",title:"QA API",description:"",techStack:[],bullets:["Original shared bullet"]}]};
function member(consent=true){return stubMethod(db.user,"findUnique",async()=>({instituteId,profile:{careerJson:JSON.stringify({...defaultCareer,mentorConsent:consent})}}));}
async function authenticated(role:string,run:()=>Promise<void>){const token=await signToken({userId:owner,role,email:"qa@example.test",sessionId:crypto.randomUUID()});const restores=[stubMethod(require("next/headers"),"cookies",async()=>new RequestCookies(new Headers({cookie:`vantory_session=${token}`}))),stubMethod(db.authSession,"findUnique",async()=>({userId:owner,revokedAt:null,expiresAt:future})),stubMethod(db.user,"findUnique",async()=>({id:owner,role,name:"QA",email:"qa@example.test",isActive:true,emailVerifiedAt:original,createdAt:original,instituteId,profile:{careerJson:JSON.stringify({...defaultCareer,mentorConsent:true})}}))];try{await run();}finally{restores.reverse().forEach(r=>r());}}
function post(body:unknown){return new Request("http://localhost/api/candidate/resume-reviews",{method:"POST",body:JSON.stringify(body)});}
test("Feedback states distinguish revoked, expired and reviewed without losing archived comments",()=>{assert.equal(feedbackStatus({status:"REVOKED",expiresAt:original}),"REVOKED");assert.equal(feedbackStatus({status:"REVIEWED",expiresAt:original}),"EXPIRED");assert.equal(feedbackStatus({status:"OPEN",expiresAt:future}),"REQUESTED");assert.equal(feedbackStatus({status:"REVIEWED",expiresAt:future}),"REVIEWED");});
test("Comment anchors display the original snapshot bullet and safely ignore malformed anchors",()=>{assert.deepEqual(commentContext(JSON.stringify({section:"projects",itemId:"project",bulletIndex:0}),snapshot),{label:"Project: QA API",bullet:"Original shared bullet"});for(const raw of ["bad",JSON.stringify({section:"projects",itemId:"project",bulletIndex:-1}),JSON.stringify({section:"education",itemId:"project",bulletIndex:0})])assert.equal(commentContext(raw,snapshot),null);});
test("Inbox filters and pagination stay owner-scoped and omit snapshots and reviewer identifiers",async()=>{const restores=[member(),stubMethod(db.resumeReviewRequest,"count",async({where}:any)=>{assert.equal(where.userId,owner);assert.equal(where.status,"REVOKED");return 26;}),stubMethod(db.resumeReviewRequest,"findMany",async({where,skip,take,select}:any)=>{assert.equal(where.userId,owner);assert.equal(skip,25);assert.equal(take,25);assert.equal(select.snapshotJson,undefined);return [{id:reviewId,resumeId,instituteId,title:"QA",status:"REVOKED",expiresAt:original,createdAt:original,resumeRevision:original,snapshotJson:"PRIVATE SNAPSHOT",comments:[{id:commentId,text:"Improve evidence",resolvedAt:null,createdAt:original,reviewerId:"private"}]}];}),stubMethod(db.institute,"findMany",async()=>[{id:instituteId,name:"College"}])];try{const result=await candidateFeedback(owner,new URLSearchParams({status:"REVOKED",page:"2"}));assert.equal(result.total,26);assert.equal(result.reviews![0].openComments,1);assert.doesNotMatch(JSON.stringify(result),/PRIVATE SNAPSHOT|reviewerId/);}finally{restores.reverse().forEach(r=>r());}});
test("Feedback detail rejects another candidate's review and invalid identifiers",async()=>{const restores=[member(),stubMethod(db.resumeReviewRequest,"findFirst",async({where}:any)=>{assert.equal(where.userId,owner);return null;})];try{await assert.rejects(()=>candidateFeedback(owner,new URLSearchParams({id:reviewId})),/not found/);await assert.rejects(()=>candidateFeedback(owner,new URLSearchParams({id:"bad"})),/Invalid/);}finally{restores.reverse().forEach(r=>r());}});
test("Archived feedback remains accessible to its candidate with sharing off and detects a newer saved revision",async()=>{const restores=[member(false),stubMethod(db.resumeReviewRequest,"findFirst",async()=>({id:reviewId,resumeId,instituteId,title:"QA",status:"REVOKED",createdAt:original,expiresAt:original,resumeRevision:original,snapshotJson:JSON.stringify(snapshot),comments:[{id:commentId,text:"Add evidence",createdAt:original,resolvedAt:null,anchorJson:JSON.stringify({section:"projects",itemId:"project",bulletIndex:0})}]})),stubMethod(db.resume,"findFirst",async()=>({id:resumeId,updatedAt:revised})),stubMethod(db.institute,"findUnique",async()=>({name:"College"}))];try{const result=await candidateFeedback(owner,new URLSearchParams({id:reviewId}));assert.equal(result.review!.sharingActive,false);assert.equal(result.review!.canRequestAgain,false);assert.equal(result.review!.revisionChanged,true);assert.equal(result.review!.comments[0].context?.bullet,"Original shared bullet");assert.equal("snapshotJson" in result.review!,false);}finally{restores.reverse().forEach(r=>r());}});
test("Feedback alerts disappear when mentor consent is off and only query current active unresolved reviews",async()=>{let queries=0;const restores=[member(false),stubMethod(db.resumeReviewRequest,"findMany",async({where,select}:any)=>{queries++;assert.equal(where.userId,owner);assert.equal(where.instituteId,instituteId);assert.equal(where.status,"REVIEWED");assert.ok(where.expiresAt.gt instanceof Date);assert.deepEqual(where.comments.some,{OR:[{resolvedAt:null},{resolvedAt:{isSet:false}}]});assert.deepEqual(select.comments.where,where.comments.some);return [{id:reviewId,title:"QA",comments:[{createdAt:original}]}];})];try{assert.deepEqual(await feedbackReminders(owner),[]);assert.equal(queries,0);const restore=member(true);try{const alerts=await feedbackReminders(owner);assert.equal(alerts[0].href,`/feedback/${reviewId}`);assert.equal(queries,1);}finally{restore();}}finally{restores.reverse().forEach(r=>r());}});
test("Feedback API requires candidate authentication and returns private no-store responses",async()=>{assert.equal((await feedbackRoute.GET(new Request("http://localhost/api/candidate/feedback"))).status,401);await authenticated("COMPANY_ADMIN",async()=>{assert.equal((await feedbackRoute.GET(new Request("http://localhost/api/candidate/feedback"))).status,403);});await authenticated("CANDIDATE",async()=>{const restores=[stubMethod(db.resumeReviewRequest,"count",async()=>0),stubMethod(db.resumeReviewRequest,"findMany",async()=>[])];try{const response=await feedbackRoute.GET(new Request("http://localhost/api/candidate/feedback"));assert.equal(response.status,200);assert.equal(response.headers.get("Cache-Control"),"private, no-store");}finally{restores.reverse().forEach(r=>r());}});});
test("Another review requires an owned prior review, changed saved revision, fresh revision and no active duplicate",async()=>{await authenticated("CANDIDATE",async()=>{let prior:any=null,current=original,duplicate=false,created:any;const restores=[stubMethod(db.resume,"findFirst",async()=>({id:resumeId,title:"QA",updatedAt:current,contentJson:JSON.stringify(snapshot)})),stubMethod(db.resumeReviewRequest,"findFirst",async({where}:any)=>{assert.equal(where.userId,owner);return where.id ? prior : duplicate ? {id:reviewId} : null;}),stubMethod(db.resumeReviewRequest,"create",async({data}:any)=>{created=data;return {id:commentId,...data};})];const body={action:"request",resumeId,previousReviewId:reviewId,expectedResumeUpdatedAt:revised.toISOString(),expectedInstituteId:instituteId};try{assert.equal((await reviewsRoute.POST(post(body))).status,404);prior={resumeRevision:original};assert.equal((await reviewsRoute.POST(post({...body,expectedInstituteId:owner}))).status,409);assert.equal((await reviewsRoute.POST(post({...body,expectedResumeUpdatedAt:original.toISOString()}))).status,409);current=revised;assert.equal((await reviewsRoute.POST(post({...body,expectedResumeUpdatedAt:original.toISOString()}))).status,409);duplicate=true;assert.equal((await reviewsRoute.POST(post(body))).status,409);duplicate=false;assert.equal((await reviewsRoute.POST(post(body))).status,200);assert.equal(created.resumeRevision,revised);assert.equal(created.instituteId,instituteId);assert.equal(JSON.parse(created.snapshotJson).projects[0].bullets[0],"Original shared bullet");assert.equal(prior.resumeRevision,original);}finally{restores.reverse().forEach(r=>r());}});});
test("Reopening a comment cannot cross a request boundary and clears only its resolved state",async()=>{await authenticated("CANDIDATE",async()=>{let saved:any;const restores=[stubMethod(db.resumeReviewRequest,"findFirst",async({where}:any)=>{assert.equal(where.userId,owner);return {id:reviewId};}),stubMethod(db.resumeReviewComment,"updateMany",async({where,data}:any)=>{assert.equal(where.requestId,reviewId);assert.equal(where.id,commentId);saved=data;return {count:1};})];try{assert.equal((await reviewsRoute.POST(post({action:"reopen",id:reviewId,commentId}))).status,200);assert.deepEqual(saved,{resolvedAt:null});}finally{restores.reverse().forEach(r=>r());}});});
test("Legacy preferences preserve an existing feedback opt-out and reject nonboolean feedback choices",async()=>{await authenticated("CANDIDATE",async()=>{let saved:any;const restores=[stubMethod(db.profile,"findUnique",async()=>({preferencesJson:JSON.stringify({...defaultPreferences,resumeFeedback:false})})),stubMethod(db.profile,"upsert",async({update}:any)=>{saved=JSON.parse(update.preferencesJson);return {preferencesJson:update.preferencesJson};})];const preferences={applicationUpdates:false,reminders:true,preparationNudges:false};try{assert.equal((await profileRoute.PATCH(new Request("http://localhost",{method:"PATCH",body:JSON.stringify({preferences})}))).status,200);assert.equal(saved.resumeFeedback,false);assert.equal((await profileRoute.PATCH(new Request("http://localhost",{method:"PATCH",body:JSON.stringify({preferences:{...preferences,resumeFeedback:"yes"}})}))).status,400);}finally{restores.reverse().forEach(r=>r());}});});
