export type Track="SOFTWARE"|"DATA"|"SHARED";
export type QuizItem={id:string;prompt:string;options:string[];answer:number;explanation:string};
export type Topic={id:string;track:Track;title:string;skills:string[];objective:string;practice:string;resource:{title:string;url:string};quiz:QuizItem[];exercise?:"arrays"|"sql"};
const q=(id:string,prompt:string,options:string[],answer:number,explanation:string):QuizItem=>({id,prompt,options,answer,explanation});
export const TOPICS:Topic[]=[
 {id:"software-frontend",track:"SOFTWARE",title:"Frontend state and accessibility",skills:["React","TypeScript","Accessibility","JavaScript"],objective:"Build forms that remain correct under asynchronous updates and usable by keyboard users.",practice:"Build a labelled search form, handle stale responses and test keyboard focus and validation errors.",resource:{title:"MDN accessibility",url:"https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Accessibility"},quiz:[q("fe1","TypeScript types validate incoming JSON at runtime:",["Always","No; validate untrusted inputs explicitly","Only when using interfaces"],1,"TypeScript types are erased; network data needs runtime validation."),q("fe2","When a modal closes, keyboard focus should normally:",["Return to the element that opened it","Disappear","Always move to the page footer"],0,"Focus restoration helps keyboard users continue from the opening control."),q("fe3","An older search response finishes after the latest request. You should:",["Always display the last response received","Ignore or cancel outdated responses","Clear all state on every render"],1,"Request identity or cancellation prevents stale results from overwriting current state.")]},
 {id:"software-arrays",track:"SOFTWARE",title:"Arrays and complexity",skills:["DSA","JavaScript","Python"],objective:"Reason about array operations, complexity and edge cases.",practice:"Implement a first-duplicate detector and explain time and space complexity.",resource:{title:"Python data structures",url:"https://docs.python.org/3/tutorial/datastructures.html"},exercise:"arrays",quiz:[q("a1","Expected hash-set lookup time is:",["O(1)","O(n)","O(n log n)"],0,"Average lookup is constant time; collisions can worsen the worst case."),q("a2","Two nested loops each visit n elements. Time complexity is:",["O(n)","O(n^2)","O(log n)"],1,"The inner loop runs n times for each of n outer iterations."),q("a3","A duplicate detector should include a test for:",["Only sorted positive values","Empty input, negative values and repeated values","Only arrays of length 10"],1,"These cover boundary conditions and prevent assumptions about value range.")]},
 {id:"software-api",track:"SOFTWARE",title:"APIs, validation and retries",skills:["REST APIs","Node.js","FastAPI"],objective:"Build predictable request validation and error responses.",practice:"Design a create-order endpoint, including duplicate requests and invalid inputs.",resource:{title:"HTTP methods",url:"https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Methods"},quiz:[q("api1","Repeating an idempotent request has:",["The same intended effect as one request","Always twice the effect","No response"],0,"Idempotency concerns the intended server effect, not identical response bytes."),q("api2","Where must authorization be enforced?",["Only in the button visibility","On the server for each protected operation","Only at signup"],1,"Client controls can be bypassed; the server must verify the actor and resource."),q("api3","A safe retry for payment creation needs:",["A larger timeout only","A stable idempotency key and stored result","Unlimited retries"],1,"Stable keys prevent a retry from creating another payment.")]},
 {id:"software-db",track:"SOFTWARE",title:"SQL, indexes and transactions",skills:["SQL","PostgreSQL","MySQL"],objective:"Explain consistency and query performance with examples.",practice:"Design a money-transfer transaction and compare a query before and after indexing.",resource:{title:"PostgreSQL transactions",url:"https://www.postgresql.org/docs/current/tutorial-transactions.html"},quiz:[q("db1","Atomicity means:",["Every query is fast","All transaction steps commit or none do","All data is public"],1,"Atomicity prevents partially committed operations."),q("db2","An index can increase:",["Write cost and storage usage","All query results","Transaction isolation automatically"],0,"Maintaining an index costs work during inserts and updates and uses storage."),q("db3","A LEFT JOIN retains:",["Only matched left rows","All left rows, including unmatched ones","Only right rows"],1,"Unmatched right columns are NULL for retained left rows.")]},
 {id:"software-testing",track:"SOFTWARE",title:"Testing and debugging",skills:["Testing","Git","JavaScript","Python"],objective:"Test externally observable behavior and diagnose failures.",practice:"Write tests for a form API covering invalid input, ownership and concurrent changes.",resource:{title:"Node test runner",url:"https://nodejs.org/api/test.html"},quiz:[q("t1","An ownership regression test needs:",["Two users and a foreign resource","Only a screenshot","Only one valid request"],0,"A foreign resource exposes whether authorization remains enforced."),q("t2","A flaky test passes after adding sleep. Better next step:",["Increase sleep indefinitely","Synchronize with the actual completion event","Delete assertions"],1,"Event-based synchronization addresses nondeterminism."),q("t3","A conflict after a concurrent edit should:",["Silently overwrite","Preserve the draft and explain recovery","Erase both versions"],1,"Conflict handling protects each user's work.")]},
 {id:"data-sql",track:"DATA",title:"SQL aggregation and joins",skills:["SQL","PostgreSQL","MySQL"],objective:"Build correct grouped reports without losing unmatched rows.",practice:"Report customer order totals, including customers who have no orders.",resource:{title:"PostgreSQL aggregate functions",url:"https://www.postgresql.org/docs/current/tutorial-agg.html"},exercise:"sql",quiz:[q("s1","To filter aggregated totals, use:",["HAVING","WHERE SUM(total)","ORDER BY only"],0,"HAVING filters groups after aggregation."),q("s2","COUNT(column) excludes:",["NULL values","All zeros","Duplicate rows always"],0,"COUNT(column) counts non-NULL values; COUNT(*) counts rows."),q("s3","Adding an order-date filter in WHERE after a LEFT JOIN can:",["Remove unmatched customers","Always retain unmatched customers","Create an index"],0,"A WHERE condition on right-hand columns can reject NULL unmatched rows.")]},
 {id:"data-quality",track:"DATA",title:"Data cleaning and validation",skills:["Python","Pandas","Excel"],objective:"Identify missing values, duplicates and inconsistent definitions.",practice:"Create a data quality checklist before calculating placement rate.",resource:{title:"Pandas missing data",url:"https://pandas.pydata.org/docs/user_guide/missing_data.html"},quiz:[q("dq1","Before removing duplicate rows, identify:",["The business key and valid repetition","Only the row color","Only table length"],0,"Repeated transactions may be valid; a business key determines uniqueness."),q("dq2","A placement rate needs:",["A documented eligible population and time window","Only number of offers","All historical accounts"],0,"A clear denominator and window make the metric interpretable."),q("dq3","Missing salary should usually be:",["Invented from a likely value","Marked missing with documented handling","Set to the highest salary"],1,"Missing data should not silently become a factual value.")]},
 {id:"data-statistics",track:"DATA",title:"Statistics and experimentation",skills:["Statistics","Python"],objective:"Explain uncertainty, outliers and experiment design.",practice:"Compare mean and median salary and define checks for a conversion experiment.",resource:{title:"NIST statistics handbook",url:"https://www.itl.nist.gov/div898/handbook/"},quiz:[q("st1","Median is often useful for salary data because:",["It is less sensitive to extreme values","It always equals mean","It removes missing values"],0,"Extreme salaries can shift the mean substantially."),q("st2","Correlation proves causation:",["Always","Only with a large dataset","No"],2,"Confounding and selection can create correlations without causation."),q("st3","A randomized experiment aims to:",["Balance confounders between groups","Guarantee a positive result","Remove all uncertainty"],0,"Random assignment reduces systematic group differences.")]},
 {id:"data-dashboard",track:"DATA",title:"Metrics and dashboard storytelling",skills:["Power BI","Tableau","Excel"],objective:"Use defined metrics and clear visual comparisons.",practice:"Design a college placement dashboard with numerator, denominator and cohort filters.",resource:{title:"Power BI design guidance",url:"https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboards-design-tips"},quiz:[q("dash1","A good dashboard should:",["Hide filters and definitions","State metric definitions and active filters","Use only 3D charts"],1,"Definitions and filters provide necessary context."),q("dash2","For a month-by-month trend, a useful chart is:",["Line chart","Unlabeled pie chart","Randomized bars"],0,"Line charts make chronological trends visible."),q("dash3","An unavailable measurement should display:",["A plausible estimate as fact","Not measured / unavailable","100%"],1,"Explicit missingness prevents misleading comparisons.")]},
 {id:"aptitude-numerical",track:"SHARED",title:"Numerical aptitude",skills:["Aptitude"],objective:"Practise ratios, percentages and interpretation.",practice:"Solve percentage-change questions and explain each denominator.",resource:{title:"NCERT mathematics resources",url:"https://ncert.nic.in/textbook.php"},quiz:[q("n1","A value rises from 80 to 100. Percentage increase?",["20%","25%","80%"],1,"Increase is 20 divided by original 80: 25%."),q("n2","A price rises by 10%, then falls by 10%. Net change?",["No change","1% decrease","1% increase"],1,"1.1 * 0.9 = 0.99."),q("n3","Ratio 2:3 with total 50. Smaller share?",["20","25","30"],0,"There are 5 shares, each worth 10; two shares are 20.")]},
 {id:"aptitude-reasoning",track:"SHARED",title:"Logical reasoning",skills:["Reasoning"],objective:"Distinguish valid deductions from assumptions.",practice:"Explain why a conclusion follows, or identify the missing premise.",resource:{title:"OpenStax logical reasoning",url:"https://openstax.org/books/contemporary-mathematics/pages/2-introduction"},quiz:[q("r1","All A are B. All B are C. Therefore:",["All A are C","All C are A","No A are C"],0,"Subset inclusion is transitive."),q("r2","If passing requires attendance, a person who passed:",["Must have met attendance requirement","Must have highest attendance","Needs no attendance"],0,"Attendance is a necessary condition, not evidence of a maximum."),q("r3","The sequence 2, 4, 8, 16 most naturally continues:",["18","24","32"],2,"Under the doubling rule the next term is 32; a finite sequence is not mathematically unique.")]},
 {id:"communication",track:"SHARED",title:"Communication and project evidence",skills:["Communication"],objective:"Explain real contributions clearly without exaggeration.",practice:"Record or write a two-minute project explanation: problem, action, checks and result.",resource:{title:"Purdue resume guidance",url:"https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/index.html"},quiz:[q("c1","A credible project explanation includes:",["Your specific contribution and checks","Only buzzwords","A fabricated production metric"],0,"Concrete contributions and checks support the claim."),q("c2","When you do not know an answer:",["Invent a confident claim","Explain what you know and how you would investigate","Repeat the question"],1,"Stated limits and a sound investigation are useful evidence."),q("c3","STAR stands for:",["Situation, Task, Action, Result","Skills, Tools, Awards, Rank","System, Test, API, Runtime"],0,"STAR structures a real behavioral example.")]}
];
export function publicTopic(t:Topic){return {...t,quiz:t.quiz.map(({answer,explanation,...item})=>item)};}
export function gradeQuiz(t:Topic,answers:unknown){
 if(!Array.isArray(answers) || answers.length!==t.quiz.length || !answers.every(a=>a && typeof a.id==="string" && Number.isInteger(a.choice)))throw new Error("Answer every question.");
 if(new Set(answers.map(a=>a.id)).size!==t.quiz.length || !t.quiz.every(q=>answers.some(a=>a.id===q.id && a.choice>=0 && a.choice<q.options.length)))throw new Error("Invalid quiz answers.");
 const review=t.quiz.map(q=>{const choice=answers.find(a=>a.id===q.id).choice;return {id:q.id,prompt:q.prompt,correct:choice===q.answer,correctChoice:q.answer,explanation:q.explanation};});
 return {score:Math.round(review.filter(r=>r.correct).length/review.length*100),review,assessmentVersion:"knowledge-check.v1"};
}
