export type ExecutionCase = {input:string;expected:string} | {setup:string;expected:string};
const pythonStarter = 'import json\nimport sys\n\ndata = json.load(sys.stdin)\n# Compute the result, then print it in the required format.\n';
export const EXERCISES = {
 arrays:{title:"First repeated value",statement:"Read a JSON array of integers from standard input. Print the first value encountered a second time, or null if all values are unique. Example: [2,1,2,1] → 2. Submit a complete Python 3 program.",language:"python",starter:pythonStarter},
 frequency:{title:"Integer frequency report",statement:"Read a JSON array of integers. Print a compact JSON array of [value,count] pairs sorted by value, with no spaces. Example: [2,1,2] → [[1,1],[2,2]]. Empty input → []. Submit a complete Python 3 program.",language:"python",starter:pythonStarter},
 brackets:{title:"Balanced brackets",statement:'Read a JSON string containing only (), [] and {}. Print true if every bracket is matched and properly nested; otherwise print false. Empty string is valid. Examples: "([])" → true; "([)]" → false. Submit a complete Python 3 program.',language:"python",starter:pythonStarter},
 intervals:{title:"Merge overlapping intervals",statement:"Read a JSON array of [start,end] integer pairs, each start ≤ end. Merge overlapping or touching intervals and sort by start. Print compact JSON with no spaces. Example: [[5,7],[1,3],[3,6]] → [[1,7]]. Empty input → []. Submit a complete Python 3 program.",language:"python",starter:pythonStarter},
 sql:{title:"Customer order totals",statement:"SQLite tables: customers(id INTEGER,name TEXT), orders(id INTEGER,customer_id INTEGER,total INTEGER). Return customer name and SUM(total), including zero for customers without orders. Sort by customer id. Submit one SELECT or WITH query only.",language:"sql",starter:"SELECT c.name, COALESCE(SUM(o.total), 0)\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.id, c.name\nORDER BY c.id;"},
 "sql-paid":{title:"Paid orders without losing customers",statement:"SQLite tables: customers(id INTEGER,name TEXT), orders(id INTEGER,customer_id INTEGER,total INTEGER,status TEXT). Return customer name and sum of PAID order totals, including zero for customers with no paid orders. Sort by customer id. Submit one SELECT or WITH query only.",language:"sql",starter:"SELECT c.name\nFROM customers c\nORDER BY c.id;"},
 "sql-ranking":{title:"Highest-value customer per region",statement:"SQLite table: customers(id INTEGER,name TEXT,region TEXT,revenue INTEGER). Return region, name and revenue for the highest-revenue customer in each region. On a tie choose the smallest customer id. Sort regions ascending. Submit one SELECT or WITH query only.",language:"sql",starter:"SELECT region, name, revenue\nFROM customers\nORDER BY region;"},
 "sql-monthly":{title:"Monthly paid revenue",statement:"SQLite table: orders(id INTEGER,ordered_at TEXT,total INTEGER,status TEXT). ordered_at is YYYY-MM-DD. Return month (YYYY-MM), paid order count and paid revenue sum. Include only months with PAID orders; sort by month. Submit one SELECT or WITH query only.",language:"sql",starter:"SELECT substr(ordered_at, 1, 7) AS month\nFROM orders\nORDER BY month;"}
} as const;
export type ExerciseId = keyof typeof EXERCISES;
const customers = "CREATE TABLE customers(id INTEGER,name TEXT); CREATE TABLE orders(id INTEGER,customer_id INTEGER,total INTEGER);";
const paid = "CREATE TABLE customers(id INTEGER,name TEXT); CREATE TABLE orders(id INTEGER,customer_id INTEGER,total INTEGER,status TEXT);";
const ranking = "CREATE TABLE customers(id INTEGER,name TEXT,region TEXT,revenue INTEGER);";
const monthly = "CREATE TABLE orders(id INTEGER,ordered_at TEXT,total INTEGER,status TEXT);";
const cases:Record<ExerciseId,ExecutionCase[]> = {
 arrays:[{input:"[2,1,2,1]",expected:"2"},{input:"[]",expected:"null"},{input:"[-1,0,3,-1]",expected:"-1"},{input:"[1,2,3]",expected:"null"}],
 frequency:[{input:"[2,1,2]",expected:"[[1,1],[2,2]]"},{input:"[]",expected:"[]"},{input:"[0,-2,-2,0,0]",expected:"[[-2,2],[0,3]]"},{input:"[5]",expected:"[[5,1]]"}],
 brackets:[{input:'"([]){}"',expected:"true"},{input:'"([)]"',expected:"false"},{input:'""',expected:"true"},{input:'")("',expected:"false"},{input:'"(("',expected:"false"}],
 intervals:[{input:"[[5,7],[1,3],[3,6]]",expected:"[[1,7]]"},{input:"[]",expected:"[]"},{input:"[[-4,-1],[2,2],[0,1]]",expected:"[[-4,-1],[0,1],[2,2]]"},{input:"[[1,10],[2,3],[1,10]]",expected:"[[1,10]]"}],
 sql:[{setup:customers+" INSERT INTO customers VALUES(1,'A'),(2,'B'); INSERT INTO orders VALUES(1,1,10),(2,1,20);",expected:"A|30\nB|0"},{setup:customers+" INSERT INTO customers VALUES(1,'A');",expected:"A|0"}],
 "sql-paid":[{setup:paid+" INSERT INTO customers VALUES(1,'A'),(2,'B'),(3,'C'); INSERT INTO orders VALUES(1,1,10,'PAID'),(2,1,20,'CANCELLED'),(3,2,40,'PENDING');",expected:"A|10\nB|0\nC|0"},{setup:paid+" INSERT INTO customers VALUES(1,'A'),(2,'A'); INSERT INTO orders VALUES(1,1,5,'PAID'),(2,1,7,'PAID'),(3,2,0,'PAID');",expected:"A|12\nA|0"},{setup:paid,expected:""}],
 "sql-ranking":[{setup:ranking+" INSERT INTO customers VALUES(1,'A','East',10),(2,'B','East',30),(3,'C','West',20);",expected:"East|B|30\nWest|C|20"},{setup:ranking+" INSERT INTO customers VALUES(8,'B','East',30),(2,'A','East',30),(4,'C','North',0);",expected:"East|A|30\nNorth|C|0"},{setup:ranking,expected:""}],
 "sql-monthly":[{setup:monthly+" INSERT INTO orders VALUES(1,'2026-01-03',10,'PAID'),(2,'2026-01-07',20,'PAID'),(3,'2026-02-01',90,'CANCELLED'),(4,'2026-03-10',5,'PAID');",expected:"2026-01|2|30\n2026-03|1|5"},{setup:monthly+" INSERT INTO orders VALUES(1,'2025-12-31',0,'PAID'),(2,'2026-12-01',15,'PAID'),(3,'2026-12-02',2,'PENDING');",expected:"2025-12|1|0\n2026-12|1|15"},{setup:monthly,expected:""}]
};
export function executionCases(exercise:ExerciseId):ExecutionCase[] {return cases[exercise].map(c=>({...c}));}
