import type { Topic, QuizItem } from "./curriculum";
type Item = [string,string[],number,string];
const variants:Record<string,Item[]> = {
  "python-frequency":[["A frequency map should initially count an unseen value as:",["Zero before incrementing","One hundred","Missing forever"],0,"Start at zero and increment for the first occurrence."],["For deterministic numeric order, sort:",["Integer keys numerically","String representations only","Input length"],0,"Lexical ordering would put 10 before 2."],["The sum of all counts should equal:",["Number of distinct values","Input length","Largest value"],1,"Each input element contributes exactly once."]],
  "python-brackets":[["Which collection follows last-in-first-out?",["Stack","Queue","Sorted set"],0,"A stack removes the latest pushed element."],["The input ([)] is:",["Balanced because counts match","Invalid because nesting is wrong","Empty"],1,"Bracket counts alone do not validate order."],["An empty bracket string is valid in this exercise:",["True","False","Only with spaces"],0,"It has no unmatched brackets."]],
  "python-intervals":[["A contained interval should:",["Shrink the current end","Keep the maximum end","Split into duplicates"],1,"The merged range must contain both inputs."],["The cost of sorting n intervals is typically:",["O(n log n)","O(1)","O(log n)"],0,"Sorting dominates the linear merge pass."],["An empty interval list produces:",["An empty list","One zero interval","An exception always"],0,"There are no ranges to merge."]],
  "sql-paid":[["A WHERE predicate on an unmatched right-side value can:",["Discard the left row","Automatically make it zero","Create a paid order"],0,"NULL comparisons fail the predicate and remove the row."],["COALESCE(NULL, 0) returns:",["NULL","0","1"],1,"COALESCE selects the first non-NULL argument."],["An inner join to paid orders omits:",["Customers without paid orders","All paid orders","Only duplicate names"],0,"An inner join requires a matching right row."]],
  "sql-ranking":[["With tied revenue, a stable winner needs:",["A documented secondary ordering key","Random row order","No ORDER BY"],0,"A deterministic tie rule makes results reproducible."],["ROW_NUMBER and RANK differ for ties because:",["ROW_NUMBER assigns distinct positions","RANK always removes ties","They never differ"],0,"ROW_NUMBER assigns one position per row."],["The window output can be filtered in:",["An outer SELECT or CTE query","A table deletion","An index name"],0,"Use an outer query to filter the computed row number."]],
  "sql-monthly":[["2025-12 and 2026-12 should be:",["Separate reporting months","Always one group","Removed"],0,"The year is part of the month key."],["COUNT(*) after filtering PAID counts:",["Paid rows including zero totals","Only positive revenue","All statuses"],0,"COUNT(*) counts each retained row."],["An exercise asking for months with paid orders only should omit:",["Months with no paid orders","Months with zero-valued paid orders","The year"],0,"The inclusion rule depends on status, not positive revenue."]],
  "software-frontend":[["A form field needs an accessible name. Prefer:",["A linked label element","Only placeholder text","Only a colour"],0,"A linked label provides a persistent accessible name."],["An effect subscribes to events. On cleanup:",["Remove that subscription","Add another subscription","Reset all props"],0,"Cleanup prevents duplicate subscriptions and leaks."],["A discriminated union helps:",["Validate remote JSON automatically","Represent exclusive states and narrow them","Eliminate all runtime failures"],1,"It models alternatives; runtime boundaries still need validation."]],
  "software-arrays":[["A set-based duplicate detector usually needs extra space:",["O(n)","O(1) always","O(n squared)"],0,"Up to n distinct values may be stored."],["Binary search needs:",["Sorted data under the comparison used","Only positive numbers","A hash table"],0,"Each comparison must identify the correct half."],["First repeated value in [3,1,3,1] when scanning left to right:",["1","3","None"],1,"The second 3 is encountered before the second 1."]],
  "software-api":[["Missing authentication should normally produce:",["401","200","A successful empty record"],0,"401 indicates missing or invalid authentication."],["Retries after transient failures should be:",["Unbounded and immediate","Bounded with backoff and duplicate-effect protection","Applied to every error forever"],1,"Retries need limits and appropriate operation semantics."],["Changing a payload while reusing an idempotency key should:",["Silently create another operation","Be rejected or handled under a documented conflict policy","Always charge twice"],1,"A stable key identifies one intended operation."]],
  "software-db":[["Rollback of a transaction should:",["Undo its uncommitted changes","Delete every table","Commit half the writes"],0,"Rollback preserves the all-or-nothing boundary."],["A unique database constraint helps prevent:",["Duplicate keys under concurrent writes","Every slow query","All authorization failures"],0,"The database enforces uniqueness even with competing requests."],["Before choosing an index, inspect:",["The query pattern and execution plan","Only the column name","Only table colour"],0,"Index usefulness depends on access patterns and selectivity."]],
  "software-testing":[["A useful assertion checks:",["An externally observable requirement","That the test file exists","Only implementation variable names"],0,"Behavioral assertions survive internal refactoring."],["A test that depends on yesterday's shared data is:",["Reliably isolated","At risk of order and environment dependence","Always faster and correct"],1,"Controlled fixtures make outcomes reproducible."],["A regression fixture should represent:",["The concrete failure condition","Only a happy-path screenshot","A random unrelated input"],0,"The fixture must expose the behavior that failed."]],
  "data-sql":[["SUM on no matching rows often needs which function for zero totals?",["COALESCE","RANDOM","DROP"],0,"COALESCE replaces a NULL aggregate with a chosen default."],["Joining each order to several items can:",["Multiply rows and distort an order-level sum","Guarantee unique orders","Always reduce row count"],0,"Respect each table's grain before aggregating."],["For exactly one row per customer, group by:",["The customer key","The order key only","No key under all circumstances"],0,"The grouping key determines report grain."]],
  "data-quality":[["A business key is:",["A field or combination identifying the business entity","Always the row number","Always a password"],0,"Business identity is independent of spreadsheet row position."],["An unknown denominator makes a percentage:",["Hard to interpret reliably","Automatically 100 percent","More precise"],0,"The eligible population is necessary context."],["Before changing missing values, record:",["The handling rule and its effect","Only the filename","A guessed replacement as fact"],0,"Documented handling keeps analysis reproducible."]],
  "data-statistics":[["Random assignment primarily reduces:",["Systematic confounding between groups","All sampling uncertainty","Every missing value"],0,"It balances group differences in expectation."],["A larger sample generally makes a valid estimate:",["Less uncertain, not automatically unbiased","Guaranteed causal","Always equal to the truth"],0,"More observations do not fix biased sampling."],["Repeatedly stopping at the first significant result can:",["Increase false-positive risk","Guarantee validity","Remove the need for a plan"],0,"Sequential analysis needs an appropriate stopping design."]],
  "data-dashboard":[["Offer count and placed-student count differ because:",["One student can have multiple offers","They must always match","Offers are never recorded"],0,"The counted entity and metric grain differ."],["A dashboard comparison needs:",["Comparable filters and time windows","More colours only","Hidden refresh dates"],0,"Context determines whether numbers are comparable."],["Drill-down should:",["Respect the viewer's access scope","Expose every student's private data","Ignore active filters"],0,"Detailed views retain authorization boundaries."]],
  "aptitude-numerical":[["120 decreases to 90. Percentage decrease:",["25 percent","30 percent","33 percent"],0,"The decrease is 30 divided by original 120."],["Three shares in a 3:2 ratio with total 100 equal:",["60","50","40"],0,"Five shares are worth 20 each."],["A 20 percent discount on 250 gives:",["200","230","150"],0,"The discount is 50."]],
  "aptitude-reasoning":[["All developers in a team use Git. Maya is on that developer team:",["Maya uses Git","Everyone using Git is on the team","Maya leads the team"],0,"The conclusion follows from membership, not the reverse implication."],["Some A are B. Therefore all A are B:",["Does not follow","Always follows","Follows if labels are short"],0,"Existence does not establish universal inclusion."],["Under the rule add 3, sequence 1,4,7 continues:",["10","14","21"],0,"The stipulated rule gives 10."]],
  "communication":[["A team achievement on your resume should clarify:",["Your own contribution","That you did everything","A guessed percentage"],0,"Distinguish individual work from the team's overall work."],["An unmeasured project outcome should be described:",["With the actual checks or observed result","With an invented growth metric","As verified by a recruiter"],0,"Metrics are optional; factual accuracy is necessary."],["When explaining a trade-off, include:",["Alternatives, constraints and your reason","Only the chosen tool name","Only confidence words"],0,"Reasoning explains the choice."]]
};
export function quizForAttempt(topic:Topic,attempts:number):QuizItem[] {
  if(attempts%2===0 || !variants[topic.id])return topic.quiz;
  return variants[topic.id].map(([prompt,options,answer,explanation],i)=>({id:`${topic.id}-b${i}`,prompt,options,answer,explanation}));
}
export function quizSet(attempts:number){return attempts%2===0?"A":"B";}
