import {InformationPage} from "@/components/site/InformationPage";

export default function PrivacyPage(){return <InformationPage title="Privacy & data use">
  <section className="space-y-2"><h2 className="text-xl font-semibold">Information used by the platform</h2><p>Vantory stores account details, candidate-provided profile and resume information, job applications, preparation attempts, interview answers and reports, opportunity records, and saved Career Studio documents in its database. Passwords are stored as hashes. Support requests are stored and may be sent by email when delivery is configured.</p></section>
  <section className="space-y-2"><h2 className="text-xl font-semibold">AI processing</h2><p>When you request AI feedback or a resume rewrite, relevant text and context are sent to Google’s Gemini API. Interview evaluation can include your answer, the question, and context from your resume and target role. Document feedback can include the draft and its source resume. Avoid including confidential information in these requests.</p></section>
  <section className="space-y-2"><h2 className="text-xl font-semibold">Applications and optional sharing</h2><p>Submitting a job application shares the submitted resume snapshot and application details with the employer. Your profile has separate controls for sharing preparation summaries and details with your joined institute. You can withdraw that optional sharing in your profile. Requesting a career-team review shares a frozen resume copy with authorized staff in your linked institute while your sharing permission and review access remain active.</p></section>
  <section className="space-y-2"><h2 className="text-xl font-semibold">Storage and requests</h2><p>Some unsaved drafts are kept in this browser’s local storage for recovery. Signing out does not necessarily remove those drafts. Use the relevant clear-draft controls on shared devices. Contact platform support through Contact Us for questions about stored data, correction, or account deletion. An automated account-deletion and retention workflow is not currently available.</p></section>
  <p className="text-sm">Updated 4 October 2026. This page describes the current product’s data flows.</p>
</InformationPage>;}
