"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Review={id:string;resumeId:string;title:string;status:string;expiresAt:string;comments:{id:string;text:string;anchorJson:string|null;resolvedAt:string|null}[]};
export function ResumeReviewPanel({resumeId,onBeforeShare}:{resumeId?:string;onBeforeShare:()=>Promise<void>}){
  const [requests,setRequests]=useState<Review[]>([]);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch("/api/candidate/resume-reviews");const j=await r.json();if(!r.ok)throw new Error(j.error);setRequests(j.requests);}
  useEffect(()=>{load().catch(e=>setNotice(e.message));},[]);
  async function action(action:string,id?:string,commentId?:string){setBusy(true);setNotice("");try{if(action==="request")await onBeforeShare();const r=await fetch("/api/candidate/resume-reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,resumeId,id,commentId})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();setNotice(action==="request"?"Saved resume shared with your linked institute career team for seven days.":"Review updated.");}catch(e){setNotice(e instanceof Error?e.message:"Unable to update review.");}finally{setBusy(false);}}
  return <section className="bg-white border rounded-2xl p-5 space-y-3"><h2 className="font-bold text-lg">Career-team review</h2><p className="text-sm text-neutral-600">Share a frozen copy of this saved resume with your linked institute. Enable mentor sharing in your <Link href="/profile" className="underline">profile</Link>. Access expires after seven days and can be revoked sooner.</p><button disabled={busy || !resumeId} className="border rounded-lg px-4 py-2 disabled:opacity-40" onClick={()=>action("request")}>Request institute review</button><p role="status" className="text-sm">{notice}</p>{requests.filter(r=>r.resumeId===resumeId).map(r=><details key={r.id} className="border rounded-lg p-4"><summary className="cursor-pointer text-sm">{r.title} · {r.status==="REVOKED"?"Revoked":new Date(r.expiresAt)<new Date()?"Expired":r.status==="REVIEWED"?"Feedback received":"Awaiting feedback"}</summary><p className="text-xs text-neutral-500 mt-2">This review concerns the copy saved when it was requested.</p>{r.status!=="REVOKED" && <button disabled={busy} onClick={()=>action("revoke",r.id)} className="underline text-sm mt-2">Revoke access</button>}{r.comments.map(c=><div key={c.id} className="border-t mt-3 pt-3 text-sm"><p>{c.text}</p>{c.anchorJson && <p className="text-xs text-neutral-500">Comment on a specific bullet in the shared snapshot.</p>}{c.resolvedAt?<p className="text-xs mt-1">Marked addressed</p>:<button disabled={busy} className="underline mt-1" onClick={()=>action("resolve",r.id,c.id)}>Mark addressed</button>}</div>)}</details>)}</section>;
}
