"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
type Review={id:string;resumeId:string;title:string;status:string;createdAt:string;expiresAt:string;resumeRevision:string;instituteName:string;currentInstituteName:string|null;currentInstituteId:string|null;sharingActive:boolean;resumeAvailable:boolean;revisionChanged:boolean;currentRevision:string|null;canRequestAgain:boolean;comments:{id:string;text:string;createdAt:string;resolvedAt:string|null;context:{label:string;bullet:string}|null}[]};
const labels:Record<string,string>={REQUESTED:"Awaiting feedback",REVIEWED:"Feedback received",REVOKED:"Access revoked",EXPIRED:"Sharing expired"};
export function FeedbackDetail({id}:{id:string}) {
  const [review,setReview]=useState<Review|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState(""),[confirmation,setConfirmation]=useState<"request"|"revoke"|null>(null);
  const load=useCallback(async()=>{setError("");try{const r=await fetch(`/api/candidate/feedback?id=${encodeURIComponent(id)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error || "Unable to open review.");setReview(j.review);}catch(e){setReview(null);setError(e instanceof Error?e.message:"Unable to open review.");}finally{setLoading(false);}},[id]);
  useEffect(()=>{void load();},[load]);
  async function action(action:string,commentId?:string) {
    if(!review)return;setBusy(true);setNotice("");setError("");
    try {const r=await fetch("/api/candidate/resume-reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id:review.id,commentId,resumeId:review.resumeId,...(action==="request" ? {previousReviewId:review.id,expectedResumeUpdatedAt:review.currentRevision,expectedInstituteId:review.currentInstituteId} : {})})});const j=await r.json();if(!r.ok)throw new Error(j.error || "Unable to update review.");setConfirmation(null);if(action==="request"){window.location.assign(`/feedback/${j.review.id}`);return;}await load();setNotice(action==="revoke" ? "Institute access revoked. Your feedback history is retained." : action==="reopen" ? "Comment reopened." : "Comment marked addressed. Your resume has not been changed.");}
    catch(e){setError(e instanceof Error?e.message:"Unable to update review.");}finally{setBusy(false);}
  }
  return <main className="max-w-4xl mx-auto space-y-6"><Link className="underline text-sm" href="/feedback">Back to feedback inbox</Link>{error && <p role="alert" className="text-red-700">{error} <button className="underline" disabled={busy} onClick={()=>void load()}>Retry</button></p>}{loading ? <p role="status">Loading review…</p> : review && <><section className="bg-white border rounded-2xl p-6 space-y-3"><div className="flex justify-between flex-wrap gap-3"><h1 className="text-2xl font-bold">{review.title}</h1><span className="border rounded-full px-3 py-1 text-sm">{labels[review.status]}</span></div><p>{review.instituteName}</p><p className="text-sm text-neutral-600">Requested {new Date(review.createdAt).toLocaleString()} · Shared resume saved {new Date(review.resumeRevision).toLocaleString()}</p><p className="text-sm">{review.sharingActive ? `Institute access expires ${new Date(review.expiresAt).toLocaleString()}.` : "Institute access is off. Your own feedback history remains available."}</p><button disabled={busy} onClick={()=>void load()} className="underline text-sm">Refresh review</button>{review.sharingActive && <button disabled={busy} className="underline text-sm ml-4" onClick={()=>setConfirmation("revoke")}>Revoke institute access</button>}</section>
    <section className="bg-white border rounded-2xl p-6 space-y-3"><h2 className="font-bold text-lg">Revise and request another review</h2><p className="text-sm">Edit and save your resume, then refresh this review. A new request shares a new frozen copy for seven days. Earlier comments stay with their original copy.</p>{review.resumeAvailable ? <><Link className="underline text-sm" href={`/resume?resumeId=${review.resumeId}`}>Revise this resume</Link><p className="text-sm">{review.revisionChanged ? "A newer saved revision is available." : "The saved resume matches this review. Save a revision before requesting another review."}</p><button disabled={busy || !review.revisionChanged || !review.canRequestAgain} onClick={()=>setConfirmation("request")} className="bg-neutral-950 text-white rounded-lg px-4 py-2 disabled:opacity-40">Request review of saved revision</button>{!review.canRequestAgain && <p className="text-sm">Join an institute and enable mentor sharing in your <Link className="underline" href="/profile">profile</Link> before sharing another copy.</p>}</> : <p className="text-sm">The source resume is no longer available. Your comments remain here.</p>}</section>
    {confirmation && <section role="group" aria-label="Confirm review sharing change" className="bg-white border rounded-xl p-5 space-y-3"><p>{confirmation==="request" ? `Share the current saved revision with ${review.currentInstituteName} for seven days? This gives its mentors access to that copy. No email is sent.` : "Revoke institute access to this shared copy? Your comments and resume will remain available to you."}</p><div className="flex gap-3"><button disabled={busy} onClick={()=>void action(confirmation)} className="bg-neutral-950 text-white rounded-lg px-4 py-2">{confirmation==="request" ? "Confirm sharing saved revision" : "Confirm revoke access"}</button><button disabled={busy} onClick={()=>setConfirmation(null)} className="border rounded-lg px-4 py-2">Keep current access</button></div></section>}
    <p role="status" className="text-sm">{notice}</p><section className="space-y-4"><h2 className="font-bold text-xl">Mentor feedback</h2><p className="text-sm text-neutral-600">Marking a comment addressed records your progress. It does not edit your resume or notify a mentor.</p>{!review.comments.length && <p className="bg-white border rounded-xl p-5">No feedback yet. Refresh after your institute reviews the shared copy.</p>}{review.comments.map(comment=><article className="bg-white border rounded-xl p-5 space-y-3" key={comment.id}><p className="text-xs text-neutral-600">Institute reviewer · {new Date(comment.createdAt).toLocaleString()} · {comment.resolvedAt ? "Addressed" : "To address"}</p>{comment.context && <blockquote className="border-l-2 pl-3 text-sm text-neutral-600"><strong>{comment.context.label} · original shared bullet</strong><p className="mt-1">{comment.context.bullet}</p></blockquote>}<p className="whitespace-pre-wrap text-sm">{comment.text}</p><button disabled={busy} onClick={()=>void action(comment.resolvedAt ? "reopen" : "resolve",comment.id)} className="underline text-sm">{comment.resolvedAt ? "Reopen comment" : "Mark addressed"}</button></article>)}</section></>}
  </main>;
}
