"use client";
import { useEffect,useState } from "react";
import { CareerProfile,CandidatePreferences,defaultCareer,defaultPreferences } from "@/lib/candidate/profile";
import { InstituteMembership } from "@/components/candidate/InstituteMembership";
type Invitation={id:string;instituteName:string;expiresAt:string};
export function ProfileForm({settingsOnly=false}:{settingsOnly?:boolean}) {
 const [profile,setProfile]=useState<Record<string,string|number|null>>({});const [career,setCareer]=useState<CareerProfile>(defaultCareer);const [preferences,setPreferences]=useState<CandidatePreferences>(defaultPreferences);const [email,setEmail]=useState("");const [notice,setNotice]=useState("");const [loaded,setLoaded]=useState(false);const [busy,setBusy]=useState(false);const [invitations,setInvitations]=useState<Invitation[]>([]);
 useEffect(()=>{Promise.all([fetch("/api/candidate/profile").then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setProfile(j.user.profile || {});setCareer(j.career);setPreferences(j.preferences);setEmail(j.user.email);setLoaded(true);}),fetch("/api/candidate/invitations").then(async r=>{const j=await r.json();if(r.ok)setInvitations(j.invitations || []);})]).catch(e=>setNotice(e.message));},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");try{const r=await fetch("/api/candidate/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settingsOnly?{preferences}:{profile:Object.fromEntries(["headline","bio","phone","location","githubUrl","linkedinUrl","portfolioUrl","skills","education","department","course","graduationYear"].filter(k=>profile[k]!==undefined).map(k=>[k,profile[k]])),career})});const j=await r.json();if(!r.ok)throw new Error(j.error);setProfile(j.profile);setNotice("Saved successfully.");window.dispatchEvent(new Event("candidate-profile-changed"));}catch(e){setNotice(e instanceof Error?e.message:"Could not save. Retry.");}finally{setBusy(false);}}
 async function respond(id:string,accept:boolean){setBusy(true);try{const r=await fetch("/api/candidate/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invitationId:id,accept})});const j=await r.json();if(!r.ok)throw new Error(j.error);setInvitations(v=>v.filter(i=>i.id!==id));if(accept)window.dispatchEvent(new Event("institute-membership-changed"));setNotice(accept?"You joined the institute. Sharing remains off until you enable it.":"Invitation declined.");}catch(e){setNotice(e instanceof Error?e.message:"Please retry.");}finally{setBusy(false);}}
 const input=(key:string,label:string,type="text")=><label key={key} className="block text-sm">{label}<input type={type} maxLength={key==="bio"?3000:600} value={String(profile[key] ?? "")} onChange={e=>setProfile(p=>({...p,[key]:key==="graduationYear"?(e.target.value?Number(e.target.value):null):e.target.value}))} className="block border rounded-lg w-full mt-1 p-3" /></label>;
 useEffect(()=>{const refresh=()=>fetch("/api/candidate/profile").then(async res=>{const result=await res.json();if(!res.ok)throw new Error(result.error);setProfile(result.user.profile || {});setCareer(result.career);}).catch(error=>setNotice(error.message));window.addEventListener("institute-membership-changed",refresh);return()=>window.removeEventListener("institute-membership-changed",refresh);},[]);
 return <div className="max-w-4xl p-6 bg-white border rounded-2xl space-y-5"><h1 className="text-2xl font-bold">{settingsOnly?"Account preferences":"Your candidate profile"}</h1><p>{email}</p><p role="status" className="text-sm">{notice}</p>{!settingsOnly && loaded && <InstituteMembership/>}{!loaded?<p>Loading profile?</p>:<form onSubmit={save} className="space-y-6">
 {settingsOnly?<div className="space-y-3">{Object.entries({applicationUpdates:"Show application updates",reminders:"Show deadline and interview reminders",preparationNudges:"Show preparation reminders",resumeFeedback:"Show institute resume feedback alerts"}).map(([k,l])=><label className="block" key={k}><input type="checkbox" checked={preferences[k as keyof CandidatePreferences]} onChange={e=>setPreferences(p=>({...p,[k]:e.target.checked}))} /> {l}</label>)}<p className="text-sm text-neutral-600">These control in-app reminders. Feedback alerts appear while institute mentor sharing is enabled; past feedback stays in your inbox. Email delivery is available only when enabled by the platform.</p></div>:<>
 <p className="text-sm">Profile completion: {profile.completionScore ?? 0}%. Your details are self-reported.</p><div className="grid sm:grid-cols-2 gap-4">{[["headline","Headline"],["bio","About you"],["phone","Phone"],["location","Location"],["skills","Skills (comma separated)"],["education","Education / institution"],["department","Department"],["course","Degree / course"],["graduationYear","Graduation year","number"],["githubUrl","GitHub","url"],["linkedinUrl","LinkedIn","url"],["portfolioUrl","Portfolio","url"]].map(([k,l,t])=>input(k,l,t))}</div>
 <label className="block">Preparation track<select value={career.track} onChange={e=>setCareer(c=>({...c,track:e.target.value as CareerProfile["track"]}))} className="block border p-3 rounded-lg"><option value="SOFTWARE">Software developer</option><option value="DATA">Data analyst</option></select></label>
 {([['targetRoles','Target roles'],['preferredLocations','Preferred locations'],['workModes','Work modes: REMOTE, ONSITE, HYBRID']] as const).map(([k,l])=><label className="block" key={k}>{l} (comma separated)<input className="block border rounded-lg p-3 w-full" value={career[k].join(", ")} onChange={e=>setCareer(c=>({...c,[k]:e.target.value.split(",").map(x=>x.trim())}))}/></label>)}
 <div className="grid grid-cols-3 gap-4">{([['cgpa','CGPA /10'],['percentage','Percentage'],['activeBacklogs','Active backlogs']] as const).map(([k,l])=><label key={k}>{l}<input type="number" step={k==='activeBacklogs'?1:0.01} min={0} max={k==='cgpa'?10:100} className="block border rounded-lg p-3 w-full" value={career[k] ?? ""} onChange={e=>setCareer(c=>({...c,[k]:e.target.value?Number(e.target.value):null}))}/></label>)}</div>
 <label className="block">Availability<input className="block border p-3 rounded-lg w-full" maxLength={150} value={career.availability} onChange={e=>setCareer(c=>({...c,availability:e.target.value}))}/></label>
 <fieldset className="space-y-3 border p-4 rounded-xl"><legend>Optional sharing</legend><label className="block"><input type="checkbox" checked={career.instituteAnalyticsConsent} onChange={e=>setCareer(c=>({...c,instituteAnalyticsConsent:e.target.checked}))}/> Share preparation summaries with my joined institute</label><label className="block"><input type="checkbox" checked={career.mentorConsent} onChange={e=>setCareer(c=>({...c,mentorConsent:e.target.checked}))}/> Allow my joined institute mentors to view my preparation details</label><p className="text-sm">You can withdraw sharing at any time. Employers see the resume you submit with an application.</p></fieldset>
 </>}
 <button disabled={busy} className="bg-neutral-950 text-white px-5 py-3 rounded-xl disabled:opacity-50">{busy?"Saving?":"Save changes"}</button>
 </form>}{!settingsOnly && invitations.map(i=><div key={i.id} className="border rounded-xl p-4"><p>{i.instituteName} invited you to join its placement roster.</p><button disabled={busy} onClick={()=>respond(i.id,true)} className="underline mr-5">Accept invitation</button><button disabled={busy} onClick={()=>respond(i.id,false)} className="underline">Decline</button></div>)}</div>;
}
