"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ApplicationState} from "@/lib/application-state";
type Opportunity={id:string;title:string;company:string;url:string|null;jobDescription:string;status:string;notes:string|null;deadline:string|null;interviewAt:string|null;updatedAt:string};
const blank={title:"",company:"",url:"",jobDescription:"",notes:"",status:"SAVED",deadline:"",interviewAt:""};
export default function OpportunitiesPage(){const [items,setItems]=useState<Opportunity[]>([]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState<Opportunity>();const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/candidate/opportunities");const j=await r.json();if(!r.ok)throw new Error(j.error);setItems(j.opportunities);}
 useEffect(()=>{load().catch(e=>setNotice(e.message));},[]);
 const local=(date:string|null)=>date?new Date(Date.parse(date)-new Date(date).getTimezoneOffset()*60000).toISOString().slice(0,16):"";
 function edit(o:Opportunity){setEditing(o);setForm({...o,url:o.url || "",notes:o.notes || "",deadline:local(o.deadline),interviewAt:local(o.interviewAt)});}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch("/api/candidate/opportunities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id:editing?.id,expectedUpdatedAt:editing?.updatedAt,deadline:form.deadline?new Date(form.deadline).toISOString():null,interviewAt:form.interviewAt?new Date(form.interviewAt).toISOString():null})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();setForm(blank);setEditing(undefined);setNotice("Opportunity saved.");}catch(e){setNotice(e instanceof Error?e.message:"Unable to save. Retry.");}finally{setBusy(false);}}
 return <div className="max-w-5xl space-y-6"><div className="bg-white rounded-2xl border p-6 space-y-3"><h1 className="text-2xl font-bold">Opportunity tracker</h1><p>Track opportunities found outside Vantory, deadlines, interviews and your notes. These records and outcomes are self-reported.</p><Link className="underline" href="/jobs/applications">Vantory applications</Link><p role="status">{notice}</p></div><form onSubmit={save} className="bg-white rounded-2xl border p-6 space-y-4"><h2 className="font-bold">{editing?"Edit opportunity":"Add opportunity"}</h2><div className="grid sm:grid-cols-2 gap-4">{[["title","Role"],["company","Company"],["url","Source URL"],["deadline","Application deadline","datetime-local"],["interviewAt","Interview time","datetime-local"]].map(([k,l,t])=><label key={k}>{l}<input required={k==='title'||k==='company'} maxLength={k==='url'?2000:150} type={t || (k==='url'?'url':'text')} className="border p-3 rounded-lg block w-full" value={form[k as keyof typeof blank]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}</div><label className="block">Status<select className="block border p-3 rounded-lg" value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{["SAVED",...Object.values(ApplicationState)].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label>{[["jobDescription","Job description"],["notes","Your notes"]].map(([k,l])=><label key={k} className="block">{l}<textarea rows={4} className="block w-full border p-3 rounded-lg" maxLength={k==='notes'?4000:30000} value={form[k as keyof typeof blank]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}<button disabled={busy} className="bg-neutral-950 text-white p-3 rounded-lg">{busy?"Saving?":"Save opportunity"}</button>{editing && <button type="button" className="underline ml-4" onClick={()=>{setEditing(undefined);setForm(blank);}}>Cancel edit</button>}</form><div className="space-y-3">{items.map(o=><article key={o.id} className="bg-white border p-5 rounded-xl space-y-2"><h2 className="font-bold">{o.title} ? {o.company}</h2><p>{o.status.replaceAll("_"," ")}</p>{o.url && <a className="underline" href={o.url} target="_blank" rel="noreferrer">View source</a>}<p className="whitespace-pre-wrap text-sm">{o.notes}</p><div className="flex gap-4 flex-wrap"><button className="underline" onClick={()=>edit(o)}>Edit</button>{o.deadline && <a className="underline" href={`/api/candidate/opportunities/${o.id}/calendar?kind=deadline`}>Deadline {new Date(o.deadline).toLocaleString()} ? Add reminder</a>}{o.interviewAt && <a className="underline" href={`/api/candidate/opportunities/${o.id}/calendar`}>Interview {new Date(o.interviewAt).toLocaleString()} ? Add reminder</a>}</div></article>)}</div></div>;
}
